-- !Ups

CREATE TABLE "USERS" (
	"EMAIL" VARCHAR(50) PRIMARY KEY,
	"PASSWORD" VARCHAR(255) NOT NULL,
	"NAME" VARCHAR(255) NOT NULL
);

CREATE TABLE "GROUPS" (
	"ID" UUID PRIMARY KEY,
	"NAME" VARCHAR(255) NOT NULL,
	"OWNER" VARCHAR(50) REFERENCES "USERS" ("EMAIL")
);

CREATE TABLE "MEMBERS" (
	"ID_GROUP" UUID REFERENCES "GROUPS" ("ID"),
	"EMAIL_USER" VARCHAR(50) REFERENCES "USERS" ("EMAIL"), 
	"VIEWING" BOOLEAN NOT NULL
);

CREATE TABLE "INVITES" (
	"CREATED" BIGINT NOT NULL,
	"RECEIVER" VARCHAR(50) REFERENCES "USERS" ("EMAIL"),
	"ID_GROUP" UUID REFERENCES "GROUPS" ("ID")
);

CREATE TABLE "TASKS" (
	"CREATED" BIGINT NOT NULL,
	"ID" UUID PRIMARY KEY,
	"ID_PARENT" UUID,
	"NAME" VARCHAR(255) NOT NULL,
	"DEADLINE" TIMESTAMP,
	"DESCRIPTION" TEXT,
	"ID_GROUP" UUID REFERENCES "GROUPS" ("ID"),
	"COMPLETED" BOOLEAN NOT NULL
);

CREATE TABLE "TASK_NOTIFS" (
	"CREATED" BIGINT NOT NULL,
	"ID_TASK" UUID REFERENCES "TASKS" ("ID"),
	"ID_GROUP" UUID REFERENCES "GROUPS" ("ID") 
);

-- !Downs

DROP TABLE "TASK_NOTIFS";
DROP TABLE "INVITES";
DROP TABLE "MEMBERS";
DROP TABLE "TASKS";
DROP TABLE "GROUPS";
DROP TABLE "USERS";